# 00b — Statistiques descriptives par segment

On reprend la base obtenue à la fin du notebook 00 (périmètre final, dossiers joints unifiés, segment SA / SB) et on décrit les variables séparément dans chaque segment, puisque chaque segment aura son propre modèle.

Pour chaque segment :
1. valeurs manquantes ;
2. variables constantes ou presque ;
3. distributions et valeurs extrêmes ;
4. variables qualitatives ;
5. redondances entre variables ;
6. pouvoir discriminant (IV) ;
7. synthèse : statut provisoire de chaque variable avant la discrétisation, et export Excel.

In [4]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

import polars as pl

from utils import binning, exploration

pl.Config.set_tbl_rows(40)
pl.Config.set_tbl_cols(-1)
pl.Config.set_fmt_str_lengths(80)

ID, TARGET, DATE, SEGMENT = "gdt", "ddefaut_ndb", "datdelhis", "segment"
BASE = Path("data/processed/base_trois_segmentation.parquet")
EXPORT = Path("outputs/stat_desc_segments.xlsx")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
base = pl.read_parquet(BASE)
SEGMENTS = {s.split("_")[0]: base.filter(pl.col(SEGMENT) == s) for s in sorted(base[SEGMENT].unique())}
base.group_by(SEGMENT).agg(n=pl.len(), n_defaut=pl.col(TARGET).sum(), taux_defaut=pl.col(TARGET).mean()).sort(SEGMENT)

shape: (3, 4)
┌──────────────────┬────────┬──────────┬─────────────┐
│ segment          ┆ n      ┆ n_defaut ┆ taux_defaut │
│ ---              ┆ ---    ┆ ---      ┆ ---         │
│ str              ┆ u32    ┆ f64      ┆ f64         │
╞══════════════════╪════════╪══════════╪═════════════╡
│ SA_mono_sans_eng ┆ 78118  ┆ 449.0    ┆ 0.005748    │
│ SB_mono_avec_eng ┆ 126625 ┆ 1561.0   ┆ 0.012328    │
│ SM_multi         ┆ 58947  ┆ 284.0    ┆ 0.004818    │
└──────────────────┴────────┴──────────┴─────────────┘

## Variables analysées
On retire l'identifiant, la cible, la date d'observation, le segment (et `has_engagement`, qui le définit), les variables de fuite (poids de sondage, voir 00 §1.2), les variables constantes sur tout le périmètre (00 §1.4) et les dates brutes. Les dates seront transformées en durées plus tard (feature engineering).

In [6]:
EXCLURE = {ID, TARGET, DATE, SEGMENT, "has_engagement", "SelectionProb", "SamplingWeight", "type_PM_PP", "code_marche_v2"}
VARS = [c for c, t in base.schema.items() if c not in EXCLURE and not t.is_temporal()]
VARS_NUM = [c for c in VARS if base.schema[c].is_numeric()]
VARS_QUALI = [c for c in VARS if c not in VARS_NUM]
print(f"{len(VARS)} variables : {len(VARS_NUM)} numériques, {len(VARS_QUALI)} qualitatives")
print("qualitatives :", VARS_QUALI)

161 variables : 152 numériques, 9 qualitatives
qualitatives : ['CAUSE_SAIN_M0', 'CODITDBDF_PAR', 'CODITDBDF_PRO', 'LISTE_CODACVPRO_modif', 'CODNAF2', 'LISTE_CODNAF2', 'CODETAJUR', 'LISTE_CODETAJUR', 'CRTOC_TOK_0010']

## 3.1 Valeurs manquantes
Le manquant est gardé comme une modalité à part entière (cours ch. 2.2) : il ne sera pas imputé, il formera sa propre classe au moment de la discrétisation. On n'écarte une variable que si elle est manquante presque partout (≥ 95 %).

In [7]:
manquants = {s: exploration.missing_report(d.select(VARS)) for s, d in SEGMENTS.items()}
manq = exploration.cote_a_cote(manquants, "variable", ["taux_missing"])
print("variables avec au moins un manquant :",
      manq.filter(pl.any_horizontal(pl.col("^taux_missing_.*$") > 0)).height, "sur", len(VARS))
manq.filter(pl.any_horizontal(pl.col("^taux_missing_.*$") > 0)).sort(pl.max_horizontal(pl.col("^taux_missing_.*$")), descending=True)

variables avec au moins un manquant : 40 sur 161

shape: (40, 4)
┌─────────────────────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ variable                        ┆ taux_missing_SA ┆ taux_missing_SB ┆ taux_missing_SM │
│ ---                             ┆ ---             ┆ ---             ┆ ---             │
│ str                             ┆ f64             ┆ f64             ┆ f64             │
╞═════════════════════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ AGE_PM_EN_MOIS                  ┆ 1.0             ┆ 1.0             ┆ 1.0             │
│ RATIO_LITIGES_vs_CA             ┆ 1.0             ┆ 1.0             ┆ 1.0             │
│ LISTE_CODNAF2                   ┆ 1.0             ┆ 1.0             ┆ 0.962492        │
│ LISTE_CODETAJUR                 ┆ 1.0             ┆ 1.0             ┆ 0.91455         │
│ LISTE_CODACVPRO_modif           ┆ 1.0             ┆ 1.0             ┆ 0.0             │
│ CODACVPRO_modif                 ┆ 0.0             ┆ 0.0             ┆ 1.0             │
│ CODNAF2                         ┆ 0.987634        ┆ 0.979214        ┆ 1.0             │
│ CODETAJUR                       ┆ 0.967229        ┆ 0.955167        ┆ 1.0             │
│ CRTOC_TOK_0010                  ┆ 0.988095        ┆ 0.979341        ┆ 1.0             │
│ MVTAFF_STABILITE_2T_vs_12M      ┆ 0.988748        ┆ 0.980107        ┆ 0.964426        │
│ CODITDBDF_PRO                   ┆ 0.988095        ┆ 0.979341        ┆ 0.963069        │
│ RATIO_NBJDEB_NONAUTO_SUR_NBJDEB ┆ 0.892394        ┆ 0.572257        ┆ 0.700036        │
│ NBJDE_RATIO_A_vs_A1             ┆ 0.802184        ┆ 0.451822        ┆ 0.570733        │
│ RATIO_SOLDE_MOYEN_SUR_EPARGNE   ┆ 0.47267         ┆ 0.258575        ┆ 0.24595         │
│ RATIO_MOUV_AFF_SUR_EPARGNE      ┆ 0.399805        ┆ 0.232498        ┆ 0.213548        │
│ PART_EPARGNE_DANS_AVOIRS        ┆ 0.399805        ┆ 0.232498        ┆ 0.213548        │
│ RATIO_LITIGES_vs_AVOIRS         ┆ 0.399805        ┆ 0.232498        ┆ 0.213548        │
│ NBECR_EVOLUTION_A_vs_A1         ┆ 0.191441        ┆ 0.037726        ┆ 0.029128        │
│ NBJ_ARR_SS_max_Mm37_Mm48        ┆ 0.179344        ┆ 0.115641        ┆ 0.135037        │
│ SOLDE_EVOLUTION_T_vs_T4         ┆ 0.170486        ┆ 0.039518        ┆ 0.025989        │
│ RATIO_ECR                       ┆ 0.140185        ┆ 0.012794        ┆ 0.016422        │
│ SOLDE_EVOLUTION_T_vs_T1         ┆ 0.138867        ┆ 0.02111         ┆ 0.016014        │
│ NBJ_ARR_SS_max_Mm25_Mm36        ┆ 0.126578        ┆ 0.071779        ┆ 0.089046        │
│ SOLDE_RATIO_T_vs_HIST           ┆ 0.123365        ┆ 0.014152        ┆ 0.013046        │
│ NBJ_ARR_SS_max_Mm19_Mm24        ┆ 0.098838        ┆ 0.051048        ┆ 0.065194        │
│ NBJ_ARR_SS_max_Mm13_Mm18        ┆ 0.068371        ┆ 0.03065         ┆ 0.041648        │
│ NBJ_ARR_SS_max_Mm10_Mm12        ┆ 0.059244        ┆ 0.024505        ┆ 0.033793        │
│ NBJ_ARR_SS_max_Mm7_Mm9          ┆ 0.046225        ┆ 0.016655        ┆ 0.024327        │
│ NBJ_ARR_SS_max_Mm4_Mm6          ┆ 0.025397        ┆ 0.008766        ┆ 0.014097        │
│ NBJ_ARR_SS_max_Mm1_Mm3          ┆ 0.007117        ┆ 0.00248         ┆ 0.003766        │
│ Dfo_max_Mm1_Mm3                 ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm4_Mm6                 ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm7_Mm9                 ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm10_Mm12               ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm13_Mm18               ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm19_Mm24               ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm25_Mm36               ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ Dfo_max_Mm37_Mm48               ┆ 0.006849        ┆ 0.002338        ┆ 0.003715        │
│ anciennete_jour_sain_M0         ┆ 0.000166        ┆ 0.000008        ┆ 0.0             │
│ CAUSE_SAIN_M0                   ┆ 0.000166        ┆ 0.000008        ┆ 0.0             │
└─────────────────────────────────┴─────────────────┴─────────────────┴─────────────────┘

**Constat** : *à compléter après exécution.*

## 3.2 Variables constantes ou presque
Une variable dont une seule valeur (manquant compris) couvre au moins 99 % des dossiers d'un segment n'apporte presque rien dans ce segment. On s'attend à ce que les variables de crédit (encours, arriérés…) soient constantes à 0 dans SA, puisque ces dossiers n'ont pas d'engagement.

In [8]:
constantes = {s: exploration.constant_report(d, VARS) for s, d in SEGMENTS.items()}
const = exploration.cote_a_cote(constantes, "variable", ["part_top", "quasi_constante"])
for s in SEGMENTS:
    print(s, ": quasi constantes =", const[f"quasi_constante_{s}"].sum())
const.filter(pl.any_horizontal(pl.col("^quasi_constante_.*$"))).sort("variable")

SA : quasi constantes = 79
SB : quasi constantes = 67
SM : quasi constantes = 63

shape: (90, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ variable     ┆ part_top_SA ┆ quasi_const ┆ part_top_SB ┆ quasi_const ┆ part_top_SM ┆ quasi_const │
│ ---          ┆ ---         ┆ ante_SA     ┆ ---         ┆ ante_SB     ┆ ---         ┆ ante_SM     │
│ str          ┆ f64         ┆ ---         ┆ f64         ┆ ---         ┆ f64         ┆ ---         │
│              ┆             ┆ bool        ┆             ┆ bool        ┆             ┆ bool        │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ AGE_PM_EN_MO ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ IS           ┆             ┆             ┆             ┆             ┆             ┆             │
│ ARR_GDT      ┆ 1.0         ┆ true        ┆ 0.902815    ┆ false       ┆ 0.966818    ┆ false       │
│ CODACVPRO_mo ┆ 0.128088    ┆ false       ┆ 0.117923    ┆ false       ┆ 1.0         ┆ true        │
│ dif          ┆             ┆             ┆             ┆             ┆             ┆             │
│ CODETAJUR    ┆ 0.967229    ┆ false       ┆ 0.955167    ┆ false       ┆ 1.0         ┆ true        │
│ CODITDBDF_PA ┆ 0.991334    ┆ true        ┆ 0.994014    ┆ true        ┆ 0.996421    ┆ true        │
│ R            ┆             ┆             ┆             ┆             ┆             ┆             │
│ CODNAF2      ┆ 0.987634    ┆ false       ┆ 0.979214    ┆ false       ┆ 1.0         ┆ true        │
│ CRTAD_IND_00 ┆ 0.999616    ┆ true        ┆ 0.999771    ┆ true        ┆ 0.999491    ┆ true        │
│ 62           ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_AG_LIG ┆ 0.997299    ┆ true        ┆ 0.993493    ┆ true        ┆ 0.990076    ┆ true        │
│ DEB_2T_IND_0 ┆             ┆             ┆             ┆             ┆             ┆             │
│ 015          ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_AG_LIG ┆ 0.996339    ┆ true        ┆ 0.991005    ┆ true        ┆ 0.986106    ┆ false       │
│ DEB_IND_0015 ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_AG_NBJ ┆ 0.997299    ┆ true        ┆ 0.993493    ┆ true        ┆ 0.990076    ┆ true        │
│ DEB_2T_IND_0 ┆             ┆             ┆             ┆             ┆             ┆             │
│ 015          ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_AG_NBJ ┆ 0.997862    ┆ true        ┆ 0.994432    ┆ true        ┆ 0.991467    ┆ true        │
│ DEB_IND_0015 ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_IND_00 ┆ 0.990092    ┆ true        ┆ 0.982263    ┆ false       ┆ 0.968378    ┆ false       │
│ 10           ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_IND_03 ┆ 0.999258    ┆ true        ┆ 0.996999    ┆ true        ┆ 0.99469     ┆ true        │
│ 01           ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_MOY_MV ┆ 0.990092    ┆ true        ┆ 0.982263    ┆ false       ┆ 0.968378    ┆ false       │
│ TAFF_IND_001 ┆             ┆             ┆             ┆             ┆             ┆             │
│ 0            ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOC_TOK_00 ┆ 0.988095    ┆ false       ┆ 0.979341    ┆ false       ┆ 1.0         ┆ true        │
│ 10           ┆             ┆             ┆             ┆             ┆             ┆             │
│ CRTOP_AG_IND ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ _0038        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Dfo_max_Mm10 ┆ 0.985676    ┆ false       ┆ 0.993864    ┆ true        ┆ 0.992926    ┆ true        │
│ _Mm12        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Dfo_max_Mm13 ┆ 0.984229    ┆ false       ┆ 0.992774    ┆ true        ┆ 0.992417    ┆ true        │
│ _Mm18        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Dfo_max_Mm19 ┆ 0.984523    ┆ false       ┆ 0.992813    ┆ true        ┆ 0.992298    ┆ true        │
│ _Mm24        ┆             ┆             ┆             ┆             ┆             ┆             │
│ Dfo_max_Mm1_ ┆ 0.990246    ┆ true        ┆ 0.996438    ┆ true        ┆ 0.995182    ┆ true        │
│ Mm3          ┆             ┆             ┆             ┆             ┆             ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ nb_credit_ML ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ T__PGE       ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_ML ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ T__autre_OCM ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_ML ┆ 1.0         ┆ true        ┆ 0.999961    ┆ true        ┆ 0.999966    ┆ true        │
│ T__autre_gar ┆             ┆             ┆             ┆             ┆             ┆             │
│ antie        ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_ML ┆ 1.0         ┆ true        ┆ 0.999139    ┆ true        ┆ 0.999932    ┆ true        │
│ T__interfimo ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_ML ┆ 1.0         ┆ true        ┆ 0.999755    ┆ true        ┆ 0.999864    ┆ true        │
│ T__sans_gara ┆             ┆             ┆             ┆             ┆             ┆             │
│ ntie         ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_au ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ tre          ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_ba ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ il           ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_fl ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        │
│ ex           ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_ga ┆ 1.0         ┆ true        ┆ 0.999542    ┆ true        ┆ 0.999559    ┆ true        │
│ rantie_emise ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.895289    ┆ false       ┆ 0.690383    ┆ false       │
│ mo           ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.997528    ┆ true        ┆ 0.994453    ┆ true        │
│ mo__autre_OC ┆             ┆             ┆             ┆             ┆             ┆             │
│ M            ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.996699    ┆ true        ┆ 0.989533    ┆ false       │
│ mo__autre_ga ┆             ┆             ┆             ┆             ┆             ┆             │
│ rantie       ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.998531    ┆ true        ┆ 0.996522    ┆ true        │
│ mo__contrat_ ┆             ┆             ┆             ┆             ┆             ┆             │
│ vie          ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.916162    ┆ false       ┆ 0.740597    ┆ false       │
│ mo__crelog   ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.984458    ┆ false       ┆ 0.958912    ┆ false       │
│ mo__hypotheq ┆             ┆             ┆             ┆             ┆             ┆             │
│ ue           ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_im ┆ 1.0         ┆ true        ┆ 0.99722     ┆ true        ┆ 0.991823    ┆ true        │
│ mo__sans_gar ┆             ┆             ┆             ┆             ┆             ┆             │
│ antie        ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_pe ┆ 1.0         ┆ true        ┆ 0.80567     ┆ false       ┆ 0.856888    ┆ false       │
│ rso          ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_re ┆ 1.0         ┆ true        ┆ 0.903787    ┆ false       ┆ 0.935603    ┆ false       │
│ volving      ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_credit_tr ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 0.999983    ┆ true        │
│ esorerie     ┆             ┆             ┆             ┆             ┆             ┆             │
│ nb_tiers     ┆ 1.0         ┆ true        ┆ 1.0         ┆ true        ┆ 0.989194    ┆ false       │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

**Constat** : *à compléter après exécution.*

## 3.3 Distributions et valeurs extrêmes
Beaucoup de montants sont très asymétriques (beaucoup de 0 et quelques valeurs très grandes), donc la règle classique de l'écart interquartile signale presque toutes les valeurs non nulles comme aberrantes. On repère plutôt les queues extrêmes : le maximum dépasse 10 fois le 99ᵉ percentile.

On ne corrige pas ces valeurs pour l'instant : la discrétisation par quantiles (ch. 4) les range dans la dernière classe, ce qui neutralise leur effet. Il faudra seulement vérifier qu'il ne s'agit pas d'erreurs de saisie (valeurs négatives impossibles, codes du type 9999…).

In [6]:
quanti = {s: exploration.univariate_summary(d, VARS_NUM) for s, d in SEGMENTS.items()}
for s, t in quanti.items():
    extremes = t.filter((pl.col("p99") > 0) & (pl.col("max") > 10 * pl.col("p99")))
    print(f"=== {s} : {extremes.height} variables avec une queue extrême")
    print(extremes.select("variable", "min", "p01", "median", "p99", "max").sort("variable"))

=== SA : 46 variables avec une queue extrême
shape: (46, 6)
┌────────────────────────┬───────────────┬─────────────┬──────────────┬─────────────┬──────────────┐
│ variable               ┆ min           ┆ p01         ┆ median       ┆ p99         ┆ max          │
│ ---                    ┆ ---           ┆ ---         ┆ ---          ┆ ---         ┆ ---          │
│ str                    ┆ f64           ┆ f64         ┆ f64          ┆ f64         ┆ f64          │
╞════════════════════════╪═══════════════╪═════════════╪══════════════╪═════════════╪══════════════╡
│ CRTAD_AG_MVTAFF_IND_00 ┆ -300000.0     ┆ 0.0         ┆ 92351.0      ┆ 2.300441e6  ┆ 1.29131683e8 │
│ 10                     ┆               ┆             ┆              ┆             ┆              │
│ CRTAD_AG_SOLDE_IND_000 ┆ 0.0           ┆ 0.0         ┆ 145000.0     ┆ 1.6578e7    ┆ 3.04192e8    │
│ 9                      ┆               ┆             ┆              ┆             ┆              │
│ CRTAD_AG_SOLDE_T       ┆ -3.6552e8     ┆ -1333.0     ┆ 121333.0     ┆ 1.3316666e7 ┆ 2.5408e8     │
│ CRTAD_AG_SOLDE_T1      ┆ -3.5024e8     ┆ -5500.0     ┆ 115000.0     ┆ 1.3116333e7 ┆ 2.48207665e8 │
│ CRTAD_AG_SOLDE_T2      ┆ -3.0273e8     ┆ -10666.0    ┆ 111666.0     ┆ 1.2929e7    ┆ 2.48093333e8 │
│ CRTAD_AG_SOLDE_T3      ┆ -3.5465e8     ┆ -16666.0    ┆ 100000.0     ┆ 1.2414333e7 ┆ 2.32616999e8 │
│ CRTAD_AG_SOLDE_T4      ┆ -5.3949e8     ┆ -21333.0    ┆ 92333.0      ┆ 1.2082666e7 ┆ 2.15663333e8 │
│ CRTAD_IND_0038         ┆ -3.7292e8     ┆ -2000.0     ┆ 141000.0     ┆ 1.6576e7    ┆ 3.04192e8    │
│ CRTAD_IND_0205         ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 9.8825e6    ┆ 1.0176e9     │
│ CRTAE_AG_SLDEPA        ┆ -2333.0       ┆ 0.0         ┆ 1166.5       ┆ 1.2791997e7 ┆ 7.81923332e8 │
│ CRTAR_IND_0036         ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 664454.0    ┆ 3.45e8       │
│ CRTAT_IND_0205         ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 9.8825e6    ┆ 1.0176e9     │
│ CRTAV_IND_0165         ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 3.114896e7  ┆ 2.6837e9     │
│ CRTOC_AG_LIGCRE_2T_IND ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 3.5590e7    ┆ 1.0690e10    │
│ _0009                  ┆               ┆             ┆              ┆             ┆              │
│ CRTOC_AG_LIGCRE_IND_00 ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 5769120.5   ┆ 1.6829e9     │
│ 09                     ┆               ┆             ┆              ┆             ┆              │
│ CRTOC_AG_MVTAFF_2T_IND ┆ -3000.0       ┆ 0.0         ┆ 0.0          ┆ 510639.0    ┆ 8.0668535e7  │
│ _0010                  ┆               ┆             ┆              ┆             ┆              │
│ CRTOC_AG_MVTAFF_IND_00 ┆ -1000.0       ┆ 0.0         ┆ 0.0          ┆ 179554.0    ┆ 2.6040439e7  │
│ 10                     ┆               ┆             ┆              ┆             ┆              │
│ CRTOC_IND_0010         ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 108821.0    ┆ 6.3782577e7  │
│ CRTOC_IND_0164         ┆ -2.6347e6     ┆ 0.0         ┆ 0.0          ┆ 104500.0    ┆ 6.22719e7    │
│ CRTOC_MOY_MVTAFF_IND_0 ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 106500.0    ┆ 6.3782577e7  │
│ 010                    ┆               ┆             ┆              ┆             ┆              │
│ …                      ┆ …             ┆ …           ┆ …            ┆ …           ┆ …            │
│ NBJ_ARR_SS_max_Mm13_Mm ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 31.0        ┆ 3819.0       │
│ 18                     ┆               ┆             ┆              ┆             ┆              │
│ NBJ_ARR_SS_max_Mm19_Mm ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 29.0        ┆ 3635.0       │
│ 24                     ┆               ┆             ┆              ┆             ┆              │
│ NBJ_ARR_SS_max_Mm25_Mm ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 55.0        ┆ 3454.0       │
│ 36                     ┆               ┆             ┆              ┆             ┆              │
│ NBJ_ARR_SS_max_Mm37_Mm ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 45.0        ┆ 3089.0       │
│ 48                     ┆               ┆             ┆              ┆             ┆              │
│ NBJ_ARR_SS_max_Mm4_Mm6 ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 1.0         ┆ 4032.0       │
│ NBJ_ARR_SS_max_Mm7_Mm9 ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 6.0         ┆ 4001.0       │
│ RATIO1_PRO             ┆ -1.673893e7   ┆ 0.0         ┆ 0.0          ┆ 1366.0      ┆ 6.3895e7     │
│ RATIO_ECR              ┆ -1.0          ┆ -1.0        ┆ 0.028571     ┆ 7.0         ┆ 323.0        │
│ RATIO_MOUV_AFF_SUR_EPA ┆ 0.0           ┆ 0.0         ┆ 0.0          ┆ 0.138083    ┆ 2869.786     │
│ RGNE                   ┆               ┆             ┆              ┆             ┆              │
│ RATIO_SOLDE_MOYEN_SUR_ ┆ -489.0        ┆ -0.130137   ┆ 0.506797     ┆ 891.1665    ┆ 114605.9995  │
│ EPARGNE                ┆               ┆             ┆              ┆             ┆              │
│ SOLDE_EVOLUTION_T_vs_T ┆ -114.78979    ┆ -1.0        ┆ 0.00052      ┆ 15.504126   ┆ 22923.169268 │
│ 1                      ┆               ┆             ┆              ┆             ┆              │
│ SOLDE_EVOLUTION_T_vs_T ┆ -253.671499   ┆ -1.0        ┆ 0.125        ┆ 52.603034   ┆ 8418.417417  │
│ 4                      ┆               ┆             ┆              ┆             ┆              │
│ SOLDE_PENTE_3T         ┆ -7.6556167e7  ┆ -1.193333e6 ┆ 0.0          ┆ 1.445e6     ┆ 1.2510e8     │
│ SOLDE_PENTE_4T         ┆ -4.6349e7     ┆ -892599.7   ┆ 400.0        ┆ 1343200.2   ┆ 7.5124e7     │
│ SOLDE_PENTE_5T         ┆ -4.0961e7     ┆ -717450.0   ┆ 1133.4       ┆ 1201366.7   ┆ 4.5054e7     │
│ SOLDE_RATIO_T_vs_HIST  ┆ -60665.368399 ┆ -0.828526   ┆ 1.021655     ┆ 21.87719    ┆ 91696.677071 │
│ SOLDE_VOLATILITE_3T    ┆ 0.0           ┆ 0.0         ┆ 29055.467897 ┆ 2.8942e6    ┆ 1.4422e8     │
│ SOLDE_VOLATILITE_5T    ┆ 0.0           ┆ 0.0         ┆ 41291.170567 ┆ 3.8083e6    ┆ 1.0992e8     │
│ solde_DAV_moyen        ┆ 0.0           ┆ 0.0         ┆ 902.45       ┆ 148793.39   ┆ 3.7657e6     │
│ solde_crediteur        ┆ 0.0           ┆ 0.0         ┆ 25999.0      ┆ 4.400188e6  ┆ 1.82347251e8 │
└────────────────────────┴───────────────┴─────────────┴──────────────┴─────────────┴──────────────┘
=== SB : 56 variables avec une queue extrême
shape: (56, 6)
┌─────────────────────────┬──────────────┬────────────┬──────────────┬──────────────┬──────────────┐
│ variable                ┆ min          ┆ p01        ┆ median       ┆ p99          ┆ max          │
│ ---                     ┆ ---          ┆ ---        ┆ ---          ┆ ---          ┆ ---          │
│ str                     ┆ f64          ┆ f64        ┆ f64          ┆ f64          ┆ f64          │
╞═════════════════════════╪══════════════╪════════════╪══════════════╪══════════════╪══════════════╡
│ ARR_GDT                 ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 260.1        ┆ 424868.2     │
│ CRTAD_AG_MVTAFF_IND_001 ┆ -2.01509e6   ┆ 0.0        ┆ 215596.0     ┆ 3.158629e6   ┆ 1.46486606e8 │
│ 0                       ┆              ┆            ┆              ┆              ┆              │
│ CRTAD_AG_SOLDE_IND_0009 ┆ 0.0          ┆ 0.0        ┆ 143000.0     ┆ 1.0374e7     ┆ 1.340285e8   │
│ CRTAD_AG_SOLDE_T        ┆ -1.5388e9    ┆ -93333.0   ┆ 108333.0     ┆ 8.203e6      ┆ 1.18980833e8 │
│ CRTAD_AG_SOLDE_T1       ┆ -1.5188e9    ┆ -94166.5   ┆ 105666.0     ┆ 8.211499e6   ┆ 1.38631e8    │
│ CRTAD_AG_SOLDE_T2       ┆ -1.5218e9    ┆ -92666.0   ┆ 105666.0     ┆ 7.820666e6   ┆ 1.51445e8    │
│ CRTAD_AG_SOLDE_T3       ┆ -1.5152e9    ┆ -106333.0  ┆ 94333.0      ┆ 7.495e6      ┆ 1.16261499e8 │
│ CRTAD_AG_SOLDE_T4       ┆ -1.5417e9    ┆ -108666.0  ┆ 88000.0      ┆ 7.061833e6   ┆ 1.32229666e8 │
│ CRTAD_IND_0038          ┆ -1.5369e9    ┆ -116000.0  ┆ 128000.0     ┆ 1.0325e7     ┆ 1.340285e8   │
│ CRTAD_IND_0205          ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 5e6          ┆ 6.0187e9     │
│ CRTAE_AG_SLDEPA         ┆ -24333.0     ┆ 0.0        ┆ 85000.0      ┆ 1.1137998e7  ┆ 3.3550e8     │
│ CRTAR_IND_0036          ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 3.044575e6   ┆ 9e8          │
│ CRTAT_IND_0205          ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 5e6          ┆ 6.0187e9     │
│ CRTAV_IND_0165          ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 2.4283613e7  ┆ 1.9859e9     │
│ CRTOC_AG_LIGCRE_2T_IND_ ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 1.27844747e8 ┆ 2.0277e10    │
│ 0009                    ┆              ┆            ┆              ┆              ┆              │
│ CRTOC_AG_LIGCRE_IND_000 ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 1.9989e7     ┆ 3.1389e9     │
│ 9                       ┆              ┆            ┆              ┆              ┆              │
│ CRTOC_AG_MVTAFF_2T_IND_ ┆ -1500.0      ┆ 0.0        ┆ 0.0          ┆ 2.011809e6   ┆ 2.4096004e8  │
│ 0010                    ┆              ┆            ┆              ┆              ┆              │
│ CRTOC_AG_MVTAFF_IND_001 ┆ -333.0       ┆ 0.0        ┆ 0.0          ┆ 631684.0     ┆ 7.0056798e7  │
│ 0                       ┆              ┆            ┆              ┆              ┆              │
│ CRTOC_IND_0010          ┆ -37273.5     ┆ 0.0        ┆ 0.0          ┆ 645100.0     ┆ 1.3648e8     │
│ CRTOC_IND_0164          ┆ -1.7346e6    ┆ 0.0        ┆ 0.0          ┆ 551800.0     ┆ 1.249598e8   │
│ …                       ┆ …            ┆ …          ┆ …            ┆ …            ┆ …            │
│ RATIO_ECR               ┆ -1.0         ┆ -0.908257  ┆ 0.047619     ┆ 4.782609     ┆ 248.0        │
│ RATIO_MOUV_AFF_SUR_EPAR ┆ -0.020833    ┆ 0.0        ┆ 0.0          ┆ 0.835789     ┆ 9463.832     │
│ GNE                     ┆              ┆            ┆              ┆              ┆              │
│ RATIO_SOLDE_MOYEN_SUR_E ┆ -43199.75    ┆ -36.092556 ┆ 0.367576     ┆ 535.08325    ┆ 33180.666    │
│ PARGNE                  ┆              ┆            ┆              ┆              ┆              │
│ SOLDE_EVOLUTION_T_vs_T1 ┆ -428.606902  ┆ -3.634348  ┆ 0.001415     ┆ 17.20162     ┆ 9969.242311  │
│ SOLDE_EVOLUTION_T_vs_T4 ┆ -582.57958   ┆ -4.88281   ┆ 0.152548     ┆ 48.5555      ┆ 15281.780781 │
│ SOLDE_PENTE_3T          ┆ -5.0399667e7 ┆ -1.0977e6  ┆ 0.0          ┆ 1350916.5    ┆ 5.366125e7   │
│ SOLDE_PENTE_4T          ┆ -2.4550e7    ┆ -807500.1  ┆ 1533.4       ┆ 1138666.8    ┆ 4.3002e7     │
│ SOLDE_PENTE_5T          ┆ -1.9829e7    ┆ -650033.2  ┆ 2433.2       ┆ 1014199.9    ┆ 3.3312e7     │
│ SOLDE_RATIO_T_vs_HIST   ┆ -381332.0    ┆ -7.394675  ┆ 0.999983     ┆ 16.472525    ┆ 1.997332e6   │
│ SOLDE_VOLATILITE_3T     ┆ 0.0          ┆ 0.0        ┆ 35546.446409 ┆ 2.6928e6     ┆ 6.7953e7     │
│ SOLDE_VOLATILITE_5T     ┆ 0.0          ┆ 149.369341 ┆ 47566.949895 ┆ 3.2994e6     ┆ 7.5169e7     │
│ bilan                   ┆ 0.0          ┆ 0.0        ┆ 8.75         ┆ 400334.17    ┆ 1.6385e7     │
│ engagement              ┆ 0.7          ┆ 4.62       ┆ 1000.0       ┆ 431295.26    ┆ 1.9113e7     │
│ engagement_DAV          ┆ 0.0          ┆ 0.0        ┆ 500.0        ┆ 6100.0       ┆ 1.5528e7     │
│ engagement_credit_perso ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 35000.0      ┆ 9014337.5    │
│ engagement_immo         ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 422405.93    ┆ 4.5600e6     │
│ engagement_immo__hypoth ┆ 0.0          ┆ 0.0        ┆ 0.0          ┆ 134763.88    ┆ 2.8657e6     │
│ eque                    ┆              ┆            ┆              ┆              ┆              │
│ horsbilan               ┆ 0.0          ┆ 0.0        ┆ 500.0        ┆ 40853.28     ┆ 2.7280e6     │
│ solde_DAV_moyen         ┆ 0.0          ┆ 0.0        ┆ 1171.81      ┆ 94794.01     ┆ 3.5335e6     │
│ solde_crediteur         ┆ 0.0          ┆ 0.0        ┆ 29572.0      ┆ 2.78255e6    ┆ 4.1488868e7  │
└─────────────────────────┴──────────────┴────────────┴──────────────┴──────────────┴──────────────┘

**Constat** : *à compléter après exécution.*

## 3.4 Variables qualitatives

In [7]:
quali = {s: exploration.modality_summary(d, VARS_QUALI) for s, d in SEGMENTS.items()}
exploration.cote_a_cote(quali, "variable", ["n_modalites", "taux_missing", "modalite_top", "freq_top"])

shape: (9, 9)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ variable ┆ n_modali ┆ taux_mis ┆ modalite ┆ freq_top ┆ n_modali ┆ taux_mis ┆ modalite ┆ freq_top │
│ ---      ┆ tes_SA   ┆ sing_SA  ┆ _top_SA  ┆ _SA      ┆ tes_SB   ┆ sing_SB  ┆ _top_SB  ┆ _SB      │
│ str      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│          ┆ i64      ┆ f64      ┆ str      ┆ f64      ┆ i64      ┆ f64      ┆ str      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ CAUSE_SA ┆ 4        ┆ 0.000138 ┆ eer      ┆ 0.969571 ┆ 4        ┆ 0.000006 ┆ eer      ┆ 0.980034 │
│ IN_M0    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ CODITDBD ┆ 2        ┆ 0.0      ┆ 0000     ┆ 0.99189  ┆ 2        ┆ 0.0      ┆ 0000     ┆ 0.994796 │
│ F_PAR    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ CODITDBD ┆ 2        ┆ 0.985106 ┆ 0000     ┆ 0.997862 ┆ 2        ┆ 0.974512 ┆ 0000     ┆ 0.997222 │
│ F_PRO    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ LISTE_CO ┆ 1242     ┆ 0.829269 ┆ 7000,700 ┆ 0.134428 ┆ 1058     ┆ 0.747099 ┆ 7000,700 ┆ 0.097868 │
│ DACVPRO_ ┆          ┆          ┆ 0        ┆          ┆          ┆          ┆ 0        ┆          │
│ modif    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ CODNAF2  ┆ 154      ┆ 0.989745 ┆ 8623Z    ┆ 0.115942 ┆ 220      ┆ 0.984471 ┆ 8623Z    ┆ 0.141337 │
│ LISTE_CO ┆ 131      ┆ 0.994788 ┆ 8621Z    ┆ 0.136456 ┆ 235      ┆ 0.989852 ┆ 8621Z    ┆ 0.112791 │
│ DNAF2    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ CODETAJU ┆ 12       ┆ 0.972824 ┆ 1500     ┆ 0.369531 ┆ 12       ┆ 0.966505 ┆ 1500     ┆ 0.426986 │
│ R        ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ LISTE_CO ┆ 41       ┆ 0.986412 ┆ 1500     ┆ 0.347656 ┆ 65       ┆ 0.977833 ┆ 1500     ┆ 0.374767 │
│ DETAJUR  ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ CRTOC_TO ┆ 2        ┆ 0.990127 ┆ O        ┆ 0.973118 ┆ 2        ┆ 0.984565 ┆ O        ┆ 0.984327 │
│ K_0010   ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

**Constat** : *à compléter après exécution.* Les variables à plus de 15 modalités (CSP, code NAF…) devront être regroupées au binning (ch. 4.5) avant qu'on puisse juger leur pouvoir discriminant.

## 3.5 Redondances entre variables
Beaucoup de variables décrivent la même chose (nombre de contrats et encours d'un même produit, soldes trimestriels successifs…). On calcule la corrélation de Spearman entre toutes les paires de variables numériques, en ignorant les manquants paire par paire, sur un échantillon de 50 000 dossiers par segment. Spearman plutôt que Pearson parce qu'il capte les relations monotones non linéaires et résiste mieux aux valeurs extrêmes (ch. 3.1).

Seuil retenu : |ρ| ≥ 0,8. Le VIF sera calculé plus tard, sur les variables discrétisées qui entreront dans le modèle (ch. 3.4 et 5).

In [8]:
redondances = {s: exploration.paires_redondantes(d, VARS_NUM, seuil=0.8) for s, d in SEGMENTS.items()}
for s, p in redondances.items():
    print(f"=== {s} : {p.height} paires avec |spearman| >= 0,8")
    print(p.head(20))

=== SA : 123 paires avec |spearman| >= 0,8
shape: (20, 4)
┌─────────────────────────────┬─────────────────────────────────┬───────────┬──────────┐
│ var1                        ┆ var2                            ┆ spearman  ┆ n_commun │
│ ---                         ┆ ---                             ┆ ---       ┆ ---      │
│ str                         ┆ str                             ┆ f64       ┆ i64      │
╞═════════════════════════════╪═════════════════════════════════╪═══════════╪══════════╡
│ nb_AC_distincts             ┆ nb_DAV                          ┆ 1.0       ┆ 50000    │
│ CRTAD_IND_0205              ┆ CRTAT_IND_0205                  ┆ 1.0       ┆ 50000    │
│ CRTOC_IND_0010              ┆ CRTOC_MOY_MVTAFF_IND_0010       ┆ 1.0       ┆ 50000    │
│ CRTOC_AG_NBJDEB_2T_IND_0015 ┆ CRTOC_AG_LIGDEB_2T_IND_0015     ┆ -0.999999 ┆ 50000    │
│ nb_produits_distincts       ┆ nb_CB_diff                      ┆ 0.996836  ┆ 50000    │
│ CRTOC_AG_LIGCRE_IND_0009    ┆ CRTOC_AG_LIGCRE_2T_IND_0009     ┆ 0.995153  ┆ 50000    │
│ CRTOC_AG_NBJCRE_2T_IND_0009 ┆ CRTOC_AG_LIGCRE_2T_IND_0009     ┆ 0.994416  ┆ 50000    │
│ CRTAD_IND_0038              ┆ CRTAD_AG_SOLDE_IND_0009         ┆ 0.992785  ┆ 50000    │
│ CRTOC_AG_LIGCRE_IND_0009    ┆ CRTOC_AG_NBJCRE_2T_IND_0009     ┆ 0.992349  ┆ 50000    │
│ NBECR_EVOLUTION_A_vs_A1     ┆ RATIO_ECR                       ┆ -0.988    ┆ 40643    │
│ CRTOC_AG_LIGCRE_IND_0009    ┆ CRTOC_AG_MVTAFF_IND_0010        ┆ 0.987979  ┆ 50000    │
│ CRTOC_AG_LIGCRE_2T_IND_0009 ┆ CRTOC_AG_MVTAFF_IND_0010        ┆ 0.982943  ┆ 50000    │
│ CRTOC_AG_MVTAFF_IND_0010    ┆ RATIO_MOUV_AFF_SUR_EPARGNE      ┆ 0.982284  ┆ 30980    │
│ CRTOC_AG_MVTAFF_IND_0010    ┆ CRTOC_AG_MVTAFF_2T_IND_0010     ┆ 0.982232  ┆ 50000    │
│ CRTAD_IND_0038              ┆ CRTAD_AG_SOLDE_T                ┆ 0.980891  ┆ 50000    │
│ CRTAD_IND_0042              ┆ CRTAD_AG_NBECR_A                ┆ 0.980634  ┆ 50000    │
│ CRTOC_AG_NBJCRE_2T_IND_0009 ┆ CRTOC_AG_MVTAFF_IND_0010        ┆ 0.980105  ┆ 50000    │
│ CRTOC_IND_0301              ┆ RATIO_NBJDEB_NONAUTO_SUR_NBJDEB ┆ 0.97884   ┆ 5791     │
│ solde_DAV_moyen             ┆ solde_crediteur                 ┆ 0.977887  ┆ 50000    │
│ CRTOC_AG_MVTAFF_2T_IND_0010 ┆ RATIO_MOUV_AFF_SUR_EPARGNE      ┆ 0.976124  ┆ 30980    │
└─────────────────────────────┴─────────────────────────────────┴───────────┴──────────┘
=== SB : 123 paires avec |spearman| >= 0,8
shape: (20, 4)
┌────────────────────────────────┬──────────────────────────────────┬───────────┬──────────┐
│ var1                           ┆ var2                             ┆ spearman  ┆ n_commun │
│ ---                            ┆ ---                              ┆ ---       ┆ ---      │
│ str                            ┆ str                              ┆ f64       ┆ i64      │
╞════════════════════════════════╪══════════════════════════════════╪═══════════╪══════════╡
│ CRTAD_IND_0205                 ┆ CRTAT_IND_0205                   ┆ 1.0       ┆ 50000    │
│ nb_credit_MLT__autre_garantie  ┆ engagement_MLT__autre_garantie   ┆ 1.0       ┆ 50000    │
│ nb_credit_LCP                  ┆ engagement_credit_LCP            ┆ 1.0       ┆ 50000    │
│ nb_credit_MLT__sans_garantie   ┆ engagement_MLT__sans_garantie    ┆ 1.0       ┆ 50000    │
│ CRTAD_IND_0062                 ┆ RATIO_LITIGES_vs_AVOIRS          ┆ 1.0       ┆ 38893    │
│ nb_credit_garantie_emise       ┆ engagement_credit_garantie_emise ┆ 1.0       ┆ 50000    │
│ nb_credit_MLT__interfimo       ┆ engagement_MLT__interfimo        ┆ 1.0       ┆ 50000    │
│ nb_credit_MLT                  ┆ engagement_MLT                   ┆ 1.0       ┆ 50000    │
│ nb_Neiertz                     ┆ engagement_credit_neiertz        ┆ 0.999999  ┆ 50000    │
│ CRTOC_IND_0010                 ┆ CRTOC_MOY_MVTAFF_IND_0010        ┆ 0.999999  ┆ 50000    │
│ nb_credit_immo__contrat_vie    ┆ engagement_immo__contrat_vie     ┆ 0.999999  ┆ 50000    │
│ nb_credit_immo__autre_OCM      ┆ engagement_immo__autre_OCM       ┆ 0.999997  ┆ 50000    │
│ nb_credit_immo__sans_garantie  ┆ engagement_immo__sans_garantie   ┆ 0.999996  ┆ 50000    │
│ CRTOC_AG_NBJDEB_2T_IND_0015    ┆ CRTOC_AG_LIGDEB_2T_IND_0015      ┆ -0.999995 ┆ 50000    │
│ nb_credit_immo__autre_garantie ┆ engagement_immo__autre_garantie  ┆ 0.999994  ┆ 50000    │
│ nb_credit_immo__hypotheque     ┆ engagement_immo__hypotheque      ┆ 0.999863  ┆ 50000    │
│ nb_AC_distincts                ┆ nb_DAV                           ┆ 0.999366  ┆ 50000    │
│ nb_credit_revolving            ┆ engagement_credit_revolving      ┆ 0.998302  ┆ 50000    │
│ CRTOC_AG_NBJCRE_2T_IND_0009    ┆ CRTOC_AG_LIGCRE_2T_IND_0009      ┆ 0.996614  ┆ 50000    │
│ CRTOC_AG_LIGCRE_IND_0009       ┆ CRTOC_AG_LIGCRE_2T_IND_0009      ┆ 0.996046  ┆ 50000    │
└────────────────────────────────┴──────────────────────────────────┴───────────┴──────────┘

**Constat** : *à compléter après exécution.*

## 3.6 Pouvoir discriminant (IV)
IV calculée sur un découpage fin (10 quantiles, manquant en classe à part), avec les seuils de Siddiqi : < 0,02 inutile, 0,02-0,1 faible, 0,1-0,3 moyen, 0,3-0,5 fort, > 0,5 suspect. Une IV au-dessus de 0,5 n'est pas forcément un problème (les variables de compte sont très prédictives en Retail), mais il faut vérifier que la variable est bien connue avant la date d'observation.

In [9]:
ivs = {s: binning.iv_ranking(d, VARS, TARGET) for s, d in SEGMENTS.items()}
print(exploration.cote_a_cote({s: t.group_by("pouvoir").len() for s, t in ivs.items()}, "pouvoir", ["len"]))
exploration.cote_a_cote(ivs, "variable", ["iv", "pouvoir"]).sort(pl.max_horizontal(pl.col("^iv_.*$")), descending=True).head(30)

shape: (5, 3)
┌─────────┬────────┬────────┐
│ pouvoir ┆ len_SA ┆ len_SB │
│ ---     ┆ ---    ┆ ---    │
│ str     ┆ u32    ┆ u32    │
╞═════════╪════════╪════════╡
│ inutile ┆ 81     ┆ 70     │
│ fort    ┆ 16     ┆ 21     │
│ faible  ┆ 21     ┆ 16     │
│ suspect ┆ 21     ┆ 33     │
│ moyen   ┆ 22     ┆ 21     │
└─────────┴────────┴────────┘

shape: (30, 5)
┌─────────────────────────────────┬──────────┬────────────┬──────────┬────────────┐
│ variable                        ┆ iv_SA    ┆ pouvoir_SA ┆ iv_SB    ┆ pouvoir_SB │
│ ---                             ┆ ---      ┆ ---        ┆ ---      ┆ ---        │
│ str                             ┆ f64      ┆ str        ┆ f64      ┆ str        │
╞═════════════════════════════════╪══════════╪════════════╪══════════╪════════════╡
│ LISTE_CODACVPRO_modif           ┆ 4.049142 ┆ suspect    ┆ 0.835409 ┆ suspect    │
│ solde_crediteur                 ┆ 0.774797 ┆ suspect    ┆ 1.973666 ┆ suspect    │
│ MINSOLDE_PAR                    ┆ 0.909083 ┆ suspect    ┆ 1.826197 ┆ suspect    │
│ solde_DAV_moyen                 ┆ 0.838933 ┆ suspect    ┆ 1.799434 ┆ suspect    │
│ CRTAD_IND_0038                  ┆ 0.705754 ┆ suspect    ┆ 1.777169 ┆ suspect    │
│ CRTAD_AG_SOLDE_T                ┆ 0.702538 ┆ suspect    ┆ 1.69402  ┆ suspect    │
│ ARR_GDT                         ┆ 0.0      ┆ inutile    ┆ 1.675529 ┆ suspect    │
│ horsbilan                       ┆ 0.0      ┆ inutile    ┆ 1.659808 ┆ suspect    │
│ bilan                           ┆ 0.0      ┆ inutile    ┆ 1.602183 ┆ suspect    │
│ CRTAD_AG_SOLDE_IND_0009         ┆ 0.705091 ┆ suspect    ┆ 1.548934 ┆ suspect    │
│ CRTAD_AG_NBJDE_BB               ┆ 0.568017 ┆ suspect    ┆ 1.547008 ┆ suspect    │
│ CRTAD_IND_0015                  ┆ 0.409703 ┆ fort       ┆ 1.511717 ┆ suspect    │
│ CRTAD_AG_SOLDE_T1               ┆ 0.687861 ┆ suspect    ┆ 1.400295 ┆ suspect    │
│ CRTAD_AG_NBJDE_BA               ┆ 0.78299  ┆ suspect    ┆ 1.378411 ┆ suspect    │
│ CRTAE_AG_SLDEPA                 ┆ 0.592983 ┆ suspect    ┆ 1.314702 ┆ suspect    │
│ ENCOURS_PAR                     ┆ 0.629236 ┆ suspect    ┆ 1.248836 ┆ suspect    │
│ CRTAD_AG_SOLDE_T2               ┆ 0.699517 ┆ suspect    ┆ 1.248003 ┆ suspect    │
│ RATIO_SOLDE_MOYEN_SUR_EPARGNE   ┆ 0.338066 ┆ fort       ┆ 1.19412  ┆ suspect    │
│ CRTAD_AG_SOLDE_T3               ┆ 0.656791 ┆ suspect    ┆ 1.150026 ┆ suspect    │
│ RATIO_NBJDEB_NONAUTO_SUR_NBJDEB ┆ 0.402013 ┆ fort       ┆ 1.129066 ┆ suspect    │
│ CRTAD_AG_SOLDE_T4               ┆ 0.751877 ┆ suspect    ┆ 1.116854 ┆ suspect    │
│ solde_debiteur                  ┆ 0.0      ┆ inutile    ┆ 0.916574 ┆ suspect    │
│ NBJ_ARR_SS                      ┆ 0.0      ┆ inutile    ┆ 0.819126 ┆ suspect    │
│ anciennete_jour_sain_M0         ┆ 0.794461 ┆ suspect    ┆ 0.561382 ┆ suspect    │
│ CRTAD_AG_MVTAFF_IND_0010        ┆ 0.036707 ┆ faible     ┆ 0.755152 ┆ suspect    │
│ NBJ_ARR_SS_max_Mm1_Mm3          ┆ 0.072784 ┆ faible     ┆ 0.730672 ┆ suspect    │
│ SOLDE_EVOLUTION_T_vs_T4         ┆ 0.343013 ┆ fort       ┆ 0.682773 ┆ suspect    │
│ Dfo_max_Mm4_Mm6                 ┆ 0.608545 ┆ suspect    ┆ 0.12456  ┆ moyen      │
│ NBJDE_RATIO_A_vs_A1             ┆ 0.424759 ┆ fort       ┆ 0.596515 ┆ suspect    │
│ CODNAF2                         ┆ 0.588561 ┆ suspect    ┆ 0.212667 ┆ moyen      │
└─────────────────────────────────┴──────────┴────────────┴──────────┴────────────┘

**Constat** : *à compléter après exécution.*

## 3.7 Synthèse : statut provisoire des variables
Pour chaque segment, on regroupe les résultats dans une fiche par variable et on attribue un statut provisoire, dans cet ordre :
1. écartée si quasi constante (3.2) et peu discriminante (IV < 0,1). Une valeur rare mais très liée au défaut, comme un défaut dans les 3 derniers mois, est gardée avec une alerte ;
2. écartée si manquante à 95 % ou plus (3.1) ;
3. écartée si IV < 0,02 (3.6) ;
4. écartée si redondante : on parcourt les variables de la plus forte à la plus faible IV, et une variable corrélée (|ρ| ≥ 0,8) à une variable déjà retenue est écartée au profit de celle-ci ;
5. sinon candidate, avec une alerte si IV > 0,5.

Les qualitatives à plus de 15 modalités sont mises à part : leur IV est gonflée tant qu'elles ne sont pas regroupées. Ce statut est provisoire : la sélection définitive se fera après la discrétisation (ch. 4-5).

In [10]:
fiches = {}
for s in SEGMENTS:
    fiche = (
        ivs[s].select("variable", "iv", "pouvoir", "n_classes")
        .join(manquants[s].select("variable", "taux_missing"), on="variable")
        .join(constantes[s].select("variable", "part_top", "quasi_constante"), on="variable")
    )
    fiches[s] = exploration.preselection_variables(fiche, redondances[s]).with_columns(
        statut=pl.when(~pl.col("variable").is_in(VARS_NUM) & (pl.col("n_classes") > 15))
        .then(pl.lit("à regrouper avant jugement (> 15 modalités)"))
        .otherwise(pl.col("statut"))
    ).sort("iv", descending=True)

exploration.cote_a_cote({s: f.group_by("statut").len() for s, f in fiches.items()}, "statut", ["len"]).sort("statut")

shape: (8, 3)
┌─────────────────────────────────────────────┬────────┬────────┐
│ statut                                      ┆ len_SA ┆ len_SB │
│ ---                                         ┆ ---    ┆ ---    │
│ str                                         ┆ u32    ┆ u32    │
╞═════════════════════════════════════════════╪════════╪════════╡
│ candidate                                   ┆ 37     ┆ 29     │
│ candidate : IV > 0,5, vérifier la fuite     ┆ 9      ┆ 20     │
│ candidate : valeur rare, à surveiller       ┆ 1      ┆ 7      │
│ à regrouper avant jugement (> 15 modalités) ┆ 4      ┆ 4      │
│ écartée : non discriminante (IV < 0,02)     ┆ 13     ┆ 18     │
│ écartée : quasi constante                   ┆ 72     ┆ 55     │
│ écartée : redondante                        ┆ 22     ┆ 24     │
│ écartée : trop de manquants                 ┆ 3      ┆ 4      │
└─────────────────────────────────────────────┴────────┴────────┘

In [11]:
for s, f in fiches.items():
    print(f"=== {s} : candidates")
    print(f.filter(pl.col("statut").str.starts_with("candidate")).select("variable", "iv", "pouvoir", "taux_missing", "statut"))

=== SA : candidates
shape: (47, 5)
┌───────────────────────────────┬──────────┬─────────┬──────────────┬──────────────────────────────┐
│ variable                      ┆ iv       ┆ pouvoir ┆ taux_missing ┆ statut                       │
│ ---                           ┆ ---      ┆ ---     ┆ ---          ┆ ---                          │
│ str                           ┆ f64      ┆ str     ┆ f64          ┆ str                          │
╞═══════════════════════════════╪══════════╪═════════╪══════════════╪══════════════════════════════╡
│ MINSOLDE_PAR                  ┆ 0.909083 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ solde_DAV_moyen               ┆ 0.838933 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ anciennete_jour_sain_M0       ┆ 0.794461 ┆ suspect ┆ 0.000138     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAD_AG_NBJDE_BA             ┆ 0.78299  ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ ENCOURS_PAR                   ┆ 0.629236 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ Dfo_max_Mm4_Mm6               ┆ 0.608545 ┆ suspect ┆ 0.007028     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAD_AG_NBJDE_BB             ┆ 0.568017 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ Dfo_max_Mm1_Mm3               ┆ 0.563251 ┆ suspect ┆ 0.007028     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CAUSE_SAIN_M0                 ┆ 0.539379 ┆ suspect ┆ 0.000138     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ Dfo_max_Mm10_Mm12             ┆ 0.491959 ┆ fort    ┆ 0.007028     ┆ candidate                    │
│ Dfo_max_Mm13_Mm18             ┆ 0.428284 ┆ fort    ┆ 0.007028     ┆ candidate                    │
│ NBJ_ARR_SS_max_Mm25_Mm36      ┆ 0.421321 ┆ fort    ┆ 0.122377     ┆ candidate                    │
│ CRTAD_IND_0015                ┆ 0.409703 ┆ fort    ┆ 0.0          ┆ candidate                    │
│ CRTAD_AG_NBJDE_BC             ┆ 0.406939 ┆ fort    ┆ 0.0          ┆ candidate                    │
│ RATIO_NBJDEB_NONAUTO_SUR_NBJD ┆ 0.402013 ┆ fort    ┆ 0.885277     ┆ candidate                    │
│ EB                            ┆          ┆         ┆              ┆                              │
│ NBJ_ARR_SS_max_Mm19_Mm24      ┆ 0.401138 ┆ fort    ┆ 0.096018     ┆ candidate                    │
│ NBJ_ARR_SS_max_Mm37_Mm48      ┆ 0.380257 ┆ fort    ┆ 0.17314      ┆ candidate                    │
│ NBJ_ARR_SS_max_Mm13_Mm18      ┆ 0.351696 ┆ fort    ┆ 0.066868     ┆ candidate                    │
│ ANCIENNETE_modif              ┆ 0.347306 ┆ fort    ┆ 0.0          ┆ candidate                    │
│ SOLDE_EVOLUTION_T_vs_T4       ┆ 0.343013 ┆ fort    ┆ 0.14864      ┆ candidate                    │
│ …                             ┆ …        ┆ …       ┆ …            ┆ …                            │
│ NBJ_ARR_SS_max_Mm10_Mm12      ┆ 0.249129 ┆ moyen   ┆ 0.057908     ┆ candidate                    │
│ NBJ_ARR_SS_max_Mm7_Mm9        ┆ 0.246785 ┆ moyen   ┆ 0.045159     ┆ candidate                    │
│ RATIO_MOUV_AFF_SUR_EPARGNE    ┆ 0.232677 ┆ moyen   ┆ 0.380038     ┆ candidate                    │
│ SOLDE_PENTE_5T                ┆ 0.231257 ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ RATIO_ECR                     ┆ 0.231068 ┆ moyen   ┆ 0.124065     ┆ candidate                    │
│ CODITDBDF_PAR                 ┆ 0.217502 ┆ moyen   ┆ 0.0          ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ SOLDE_PENTE_3T                ┆ 0.198783 ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ AGE_PP_EN_MOIS                ┆ 0.198272 ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ CODACVPRO_modif               ┆ 0.195774 ┆ moyen   ┆ 0.170731     ┆ candidate                    │
│ NBJ_ARR_SS_max_Mm4_Mm6        ┆ 0.191596 ┆ moyen   ┆ 0.025318     ┆ candidate                    │
│ Dfo_max_Mm25_Mm36             ┆ 0.188562 ┆ moyen   ┆ 0.007028     ┆ candidate                    │
│ Dfo_max_Mm37_Mm48             ┆ 0.125481 ┆ moyen   ┆ 0.007028     ┆ candidate                    │
│ CRTAD_AG_NBECR_B              ┆ 0.097454 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ NBJ_ARR_SS_max_Mm1_Mm3        ┆ 0.072784 ┆ faible  ┆ 0.007272     ┆ candidate                    │
│ cod_axe_unite                 ┆ 0.050591 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ nb_produits_distincts         ┆ 0.039489 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ CRTAD_IND_0205                ┆ 0.037617 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ CRTAD_AG_MVTAFF_IND_0010      ┆ 0.036707 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ nb_tiers                      ┆ 0.029765 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ nb_crt_distincts              ┆ 0.027002 ┆ faible  ┆ 0.0          ┆ candidate                    │
└───────────────────────────────┴──────────┴─────────┴──────────────┴──────────────────────────────┘
=== SB : candidates
shape: (56, 5)
┌───────────────────────────────┬──────────┬─────────┬──────────────┬──────────────────────────────┐
│ variable                      ┆ iv       ┆ pouvoir ┆ taux_missing ┆ statut                       │
│ ---                           ┆ ---      ┆ ---     ┆ ---          ┆ ---                          │
│ str                           ┆ f64      ┆ str     ┆ f64          ┆ str                          │
╞═══════════════════════════════╪══════════╪═════════╪══════════════╪══════════════════════════════╡
│ solde_crediteur               ┆ 1.973666 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ MINSOLDE_PAR                  ┆ 1.826197 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ ARR_GDT                       ┆ 1.675529 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ horsbilan                     ┆ 1.659808 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ bilan                         ┆ 1.602183 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAD_AG_NBJDE_BB             ┆ 1.547008 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAE_AG_SLDEPA               ┆ 1.314702 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ RATIO_SOLDE_MOYEN_SUR_EPARGNE ┆ 1.19412  ┆ suspect ┆ 0.246594     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ RATIO_NBJDEB_NONAUTO_SUR_NBJD ┆ 1.129066 ┆ suspect ┆ 0.590274     ┆ candidate : IV > 0,5,        │
│ EB                            ┆          ┆         ┆              ┆ vérifier la fuite            │
│ solde_debiteur                ┆ 0.916574 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ NBJ_ARR_SS                    ┆ 0.819126 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAD_AG_MVTAFF_IND_0010      ┆ 0.755152 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ NBJ_ARR_SS_max_Mm1_Mm3        ┆ 0.730672 ┆ suspect ┆ 0.002401     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ SOLDE_EVOLUTION_T_vs_T4       ┆ 0.682773 ┆ suspect ┆ 0.034527     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ NBJDE_RATIO_A_vs_A1           ┆ 0.596515 ┆ suspect ┆ 0.462856     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ anciennete_jour_sain_M0       ┆ 0.561382 ┆ suspect ┆ 0.000006     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ RATIO_ECR                     ┆ 0.560281 ┆ suspect ┆ 0.010927     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAD_AG_NBJDE_BC             ┆ 0.556936 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ SOLDE_RATIO_T_vs_HIST         ┆ 0.551524 ┆ suspect ┆ 0.012083     ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ CRTAD_IND_0042                ┆ 0.509264 ┆ suspect ┆ 0.0          ┆ candidate : IV > 0,5,        │
│                               ┆          ┆         ┆              ┆ vérifier la fuite            │
│ …                             ┆ …        ┆ …       ┆ …            ┆ …                            │
│ engagement                    ┆ 0.308125 ┆ fort    ┆ 0.0          ┆ candidate                    │
│ CODACVPRO_modif               ┆ 0.295888 ┆ moyen   ┆ 0.252901     ┆ candidate                    │
│ engagement_DAV                ┆ 0.268142 ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ CAUSE_SAIN_M0                 ┆ 0.263829 ┆ moyen   ┆ 0.000006     ┆ candidate                    │
│ AGE_PP_EN_MOIS                ┆ 0.23379  ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ CODITDBDF_PAR                 ┆ 0.229956 ┆ moyen   ┆ 0.0          ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ CRTPI_IND_0036                ┆ 0.1896   ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ nb_credit_immo                ┆ 0.14555  ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ Dfo_max_Mm7_Mm9               ┆ 0.13506  ┆ moyen   ┆ 0.002289     ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ Dfo_max_Mm4_Mm6               ┆ 0.12456  ┆ moyen   ┆ 0.002289     ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ Dfo_max_Mm13_Mm18             ┆ 0.123546 ┆ moyen   ┆ 0.002289     ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ nb_tiers                      ┆ 0.119618 ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ Dfo_max_Mm25_Mm36             ┆ 0.114933 ┆ moyen   ┆ 0.002289     ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ Dfo_max_Mm10_Mm12             ┆ 0.1104   ┆ moyen   ┆ 0.002289     ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ Dfo_max_Mm19_Mm24             ┆ 0.108694 ┆ moyen   ┆ 0.002289     ┆ candidate : valeur rare, à   │
│                               ┆          ┆         ┆              ┆ surveiller                   │
│ nb_CB_diff                    ┆ 0.102505 ┆ moyen   ┆ 0.0          ┆ candidate                    │
│ CRTAD_IND_0205                ┆ 0.060018 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ nb_produits_distincts         ┆ 0.041052 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ nb_credit_perso               ┆ 0.029721 ┆ faible  ┆ 0.0          ┆ candidate                    │
│ cod_axe_unite                 ┆ 0.023504 ┆ faible  ┆ 0.0          ┆ candidate                    │
└───────────────────────────────┴──────────┴─────────┴──────────────┴──────────────────────────────┘

**Constat** : *à compléter après exécution.*

## 3.8 Export Excel
Un onglet par thème et par segment. Le fichier ne contient que des statistiques agrégées, jamais de lignes individuelles.

In [12]:
feuilles = {}
for s in SEGMENTS:
    feuilles |= {
        f"{s}_Fiche_variables": fiches[s],
        f"{s}_Manquants": manquants[s],
        f"{s}_Constantes": constantes[s],
        f"{s}_Stats_quanti": quanti[s],
        f"{s}_Stats_quali": quali[s],
        f"{s}_Redondances": redondances[s],
        f"{s}_IV": ivs[s],
    }
exploration.exporter_excel(feuilles, EXPORT)
print("export :", EXPORT, "|", len(feuilles), "onglets")

ModuleNotFoundError: No module named 'xlsxwriter'

### Graphique de stabilté des segement dans le temps

In [9]:
from utils.exploration import risk_rate_by_modality_over_time
stabilite = risk_rate_by_modality_over_time(
    base,
    DATE,
    "segment",
    TARGET
)

print(stabilite)

shape: (12, 5)
┌────────────┬──────────────────┬───────┬──────────┬─────────────┐
│ datdelhis  ┆ segment          ┆ n     ┆ n_defaut ┆ taux_defaut │
│ ---        ┆ ---              ┆ ---   ┆ ---      ┆ ---         │
│ date       ┆ str              ┆ u32   ┆ f64      ┆ f64         │
╞════════════╪══════════════════╪═══════╪══════════╪═════════════╡
│ 2021-01-01 ┆ SA_mono_sans_eng ┆ 19543 ┆ 108.0    ┆ 0.005526    │
│ 2021-01-01 ┆ SB_mono_avec_eng ┆ 31672 ┆ 376.0    ┆ 0.011872    │
│ 2021-01-01 ┆ SM_multi         ┆ 14668 ┆ 71.0     ┆ 0.00484     │
│ 2021-02-01 ┆ SA_mono_sans_eng ┆ 19461 ┆ 94.0     ┆ 0.00483     │
│ 2021-02-01 ┆ SB_mono_avec_eng ┆ 31738 ┆ 398.0    ┆ 0.01254     │
│ 2021-02-01 ┆ SM_multi         ┆ 14738 ┆ 65.0     ┆ 0.00441     │
│ 2021-03-01 ┆ SA_mono_sans_eng ┆ 19147 ┆ 84.0     ┆ 0.004387    │
│ 2021-03-01 ┆ SB_mono_avec_eng ┆ 31885 ┆ 401.0    ┆ 0.012576    │
│ 2021-03-01 ┆ SM_multi         ┆ 14704 ┆ 67.0     ┆ 0.004557    │
│ 2021-04-01 ┆ SA_mono_sans_eng ┆ 19967 ┆ 163.0    ┆ 0.008163    │
│ 2021-04-01 ┆ SB_mono_avec_eng ┆ 31330 ┆ 386.0    ┆ 0.01232     │
│ 2021-04-01 ┆ SM_multi         ┆ 14837 ┆ 81.0     ┆ 0.005459    │
└────────────┴──────────────────┴───────┴──────────┴─────────────┘